# Generated by Django 4.2.7 on 2024-02-01 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nro_exp', models.CharField(max_length=100)),
                ('iniciador', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto', models.TextField(blank=True, max_length=200, null=True)),
                ('nro_resol_rectorado', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_resol_CS', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'expedientes',
            },
        ),
        migrations.CreateModel(
            name='ExpedientesPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nro_exp', models.IntegerField()),
                ('objeto', models.TextField(max_length=500)),
                ('nro_resol_rectorado', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_resol_CS', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('exp_year', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('area_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_creacion', to='Exp.areas')),
            ],
            options={
                'db_table': 'expedientes_prueba',
            },
        ),
        migrations.CreateModel(
            name='Iniciadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciador', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'Iniciadores',
            },
        ),
        migrations.CreateModel(
            name='Pases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pase', models.DateTimeField(default='01')),
                ('area_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_origen', to='Exp.areas')),
                ('area_receptora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_receptora', to='Exp.areas')),
                ('nro_exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pases', to='Exp.expedientesprueba')),
            ],
            options={
                'db_table': 'expedientes_pases',
            },
        ),
        migrations.AddField(
            model_name='expedientesprueba',
            name='iniciador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exp.iniciadores'),
        ),
    ]
