# Generated by Django 5.0 on 2024-01-15 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nro_exp', models.CharField(max_length=100)),
                ('iniciador', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto', models.TextField(blank=True, max_length=200, null=True)),
                ('nro_resol_rectorado', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_resol_CS', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'expedientes',
            },
        ),
        migrations.CreateModel(
            name='ExpedientesPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default='15/01/2024')),
                ('nro_exp', models.IntegerField()),
                ('iniciador', models.CharField(max_length=100)),
                ('objeto', models.TextField(max_length=200)),
                ('nro_resol_rectorado', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_resol_CS', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'expedientes_prueba',
            },
        ),
        migrations.CreateModel(
            name='Pases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pase', models.DateTimeField(default='15')),
                ('area_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_origen', to='Exp.areas')),
                ('area_receptora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_receptora', to='Exp.areas')),
                ('nro_exp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pases', to='Exp.expedientesprueba')),
            ],
            options={
                'db_table': 'expedientes_pases',
            },
        ),
    ]
