# Generated by Django 5.0 on 2024-01-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nro_exp', models.CharField(max_length=100)),
                ('iniciador', models.CharField(max_length=100)),
                ('objeto', models.TextField(max_length=200)),
                ('nro_resol_rectorado', models.CharField(max_length=100)),
                ('nro_resol_CS', models.CharField(max_length=100)),
                ('observaciones', models.TextField(max_length=500)),
            ],
        ),
    ]
