# Generated by Django 5.0 on 2024-01-15 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientesprueba',
            name='area_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_creacion', to='Exp.areas'),
        ),
    ]
