# Generated by Django 5.0 on 2024-01-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientes',
            name='iniciador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expedientes',
            name='nro_resol_CS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expedientes',
            name='nro_resol_rectorado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expedientes',
            name='objeto',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expedientes',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
