# Generated by Django 5.0 on 2024-01-17 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0002_expedientesprueba_area_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientesprueba',
            name='fecha',
            field=models.DateTimeField(default='17/01/2024'),
        ),
        migrations.AlterField(
            model_name='pases',
            name='fecha_pase',
            field=models.DateTimeField(default='17'),
        ),
        migrations.AlterField(
            model_name='pases',
            name='nro_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pases', to='Exp.expedientesprueba'),
        ),
    ]
