# Generated by Django 5.0 on 2024-01-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0002_alter_expedientes_iniciador_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expedientes',
            table='expedientes',
        ),
    ]
