# Generated by Django 5.0 on 2024-01-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0003_alter_expedientes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedientesPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nro_exp', models.CharField(max_length=100)),
                ('iniciador', models.CharField(max_length=100)),
                ('objeto', models.TextField(max_length=200)),
                ('nro_resol_rectorado', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_resol_CS', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'expedientes_prueba',
            },
        ),
    ]
