# Generated by Django 5.0 on 2024-01-08 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0004_expedientesprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientesprueba',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
