# Generated by Django 5.0 on 2024-01-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0005_iniciadores_alter_pases_fecha_pase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iniciadores',
            table='Iniciadores',
        ),
    ]
