# Generated by Django 5.0 on 2024-01-18 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0006_alter_iniciadores_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientesprueba',
            name='iniciador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exp.iniciadores'),
        ),
    ]
