# Generated by Django 5.0 on 2024-01-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0007_alter_expedientesprueba_iniciador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientesprueba',
            name='objeto',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='pases',
            name='fecha_pase',
            field=models.DateTimeField(default='19'),
        ),
    ]
