# Generated by Django 5.0 on 2024-01-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0009_alter_expedientesprueba_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientesprueba',
            name='fecha',
            field=models.DateTimeField(default='08/01/2024'),
        ),
    ]
