# Generated by Django 5.0 on 2024-01-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0010_alter_expedientesprueba_nro_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientesprueba',
            name='exp_year',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='expedientesprueba',
            name='nro_exp',
            field=models.IntegerField(),
        ),
    ]
