# Generated by Django 5.0 on 2024-01-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0011_expedientesprueba_exp_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientesprueba',
            name='exp_year',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
