# Generated by Django 5.0 on 2024-01-19 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0012_alter_expedientesprueba_exp_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pases',
            name='fecha_pase',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
