# Generated by Django 5.0 on 2024-01-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0013_alter_pases_fecha_pase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pases',
            name='fecha_pase',
            field=models.DateTimeField(default='27'),
        ),
    ]
