# Generated by Django 5.0 on 2024-01-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0013_alter_expedientesprueba_nro_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientesprueba',
            name='fecha',
            field=models.DateTimeField(default='10/01/2024'),
        ),
    ]
