# Generated by Django 5.0 on 2024-01-10 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0014_alter_expedientesprueba_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pase', models.DateTimeField(default='10')),
                ('area', models.CharField(max_length=100)),
                ('nro_exp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='Exp.expedientes')),
            ],
            options={
                'db_table': 'expedientes_pases',
            },
        ),
    ]
