# Generated by Django 5.0 on 2024-01-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0016_areas_alter_expedientesprueba_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='areas',
            table='Areas',
        ),
    ]
