# Generated by Django 5.0 on 2024-01-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0017_alter_areas_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pases',
            name='area',
        ),
        migrations.AddField(
            model_name='pases',
            name='area_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_origen', to='Exp.areas'),
        ),
        migrations.AddField(
            model_name='pases',
            name='area_receptora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_receptora', to='Exp.areas'),
        ),
    ]
