# Generated by Django 5.0 on 2024-01-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp', '0018_remove_pases_area_pases_area_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pases',
            name='nro_exp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='Exp.expedientesprueba'),
        ),
    ]
